# Generated by Django 4.2.7 on 2023-12-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='thesis',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_thesis_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervised_thesis_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_thesis_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisApp.subjecttopic'),
        ),
    ]
