# Generated by Django 4.2.7 on 2024-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisApp', '0003_alter_thesis_abstract_alter_thesis_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='thesis_type',
        ),
        migrations.AddField(
            model_name='thesis',
            name='thesis_type',
            field=models.ManyToManyField(to='thesisApp.thesistype'),
        ),
    ]
