# Generated by Django 4.2.7 on 2024-01-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesisApp', '0004_thesistype_remove_thesis_thesis_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='thesis_type',
        ),
        migrations.AddField(
            model_name='thesis',
            name='thesis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesisApp.thesistype'),
        ),
    ]
