# Generated by Django 4.2.7 on 2024-01-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesisApp', '0005_remove_thesis_thesis_type_thesis_thesis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='thesis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesisApp.thesistype'),
        ),
    ]
